### ISSUE TITLE
tests failure due to `solve_non_negative`

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#222]
The current [test](https://github.com/discsim/frank/blob/9de2461579c95ab3b6c484be4819f4681a735967/frank/tests.py#L317) for [solve_non_negative](https://github.com/discsim/frank/blob/9de2461579c95ab3b6c484be4819f4681a735967/frank/statistical_models.py#L838) passes on python 3.8 but not 3.9+, returning an array of 0. The underlying scipy [implementation](https://github.com/scipy/scipy/blob/v1.14.0/scipy/optimize/_nnls.py#L8-L95) was updated ~6 months ago. @rbooth200, do you have an idea for a quick fix?

**Comment by rbooth200** [comment]
Hi @jeffjennings, I think this is scipy issue, not frank/python. In scipy 1.12 they changed the nnls method, and the new version does not work for frank. I *think* scipy will fix nnls in the next release (version 1.15) because I see changes on their github. For now, it might be best to require scipy<=1.11.4. When the new version releases we can require scipy<=1.11.4 for python < 3.0 and and scipy>1.15 for python3.10+.  What do you think? To me the only alternative is to hand-roll our own nnls and that isn't something I want to do.

**Comment by jeffjennings** [comment]
Yes that sounds good, thanks for the PR! With your fix there I think it's fine to close this.
