### ISSUE TITLE
plot.py

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#40]
- uv binning: @rbooth200 Can you drop your code for the faster uv binning into `plot.py` in the `docs_and_runner_jj` branch?

- Interfacing with `_HankelRegressor`: 
   * Accessing the predicted visibilities: @rbooth200 Are you open to `_HankelRegressor` returning the (predicted) deprojected visibilities directly in `sol` (rather than having to do `sol.predict_deprojected(sol.q)`? I assume you didn't do this so a user could call either `sol.predict` or `sol.predict_deprojected`, but I think that since `predict_deprojected` already corrects the visibility amplitudes for the inclination, it would be good to just return these directly in `sol` as they're as much a component of the fit as the reconstructed `I(r_k)`.

   * Accessing the observed visibilities: @rbooth200 https://github.com/discsim/frank/blob/72b249954c2946873e56548b45744a0bef490dd8/frank/radial_fitters.py#L412 
Can you pop l.412-420 out of `_build_matrices` and into another function that returns the deprojected (but amplitude-shifted) observed visibilities and weights? I know you already have `self._geometry.apply_correction`, but a function that does this _and_ corrects the amplitude of V for the inclination would be useful for calling a single function in `plot.py` to obtain the deprojected observed visibilities.  The deprojection and amplitude correction functionalities also seem outside the scope of `_build_matrices`.

**Comment by rbooth200** [comment]
I can of course do this - but I'm not convinced that its correct. 

For the 1: Have we decided whether to have a uvplot dependency yet? If so then we should use the functions in there - I can open a PR there.

For 2.1: My reason for not adding "sol.predict_deprojected(sol.q)" as a stored variable is that it was not clear to me that we would always want the same values of q - hence a function instead of a variable. We could make self.q be the default argument to these functions if you prefer.

For 2.2: I thought we agreed that frank should not modify UV data in user-facing functions. The correct thing to do is to deproject the uv data for plotting using the geometry.apply_correction. sol.predict_deprojected handles the change in amplitude of the predicted visibilities to make them consistent already.

**Comment by jeffjennings** [comment]
For 1: uvplot won't be a dependency (MT and I discussed), because MT is making casa a dependency for uvplot, which would mean to install frank a user would have to install the ~100 MB casa package.

For 2.1: Making self.q the default is a bit cleaner I think, though it was more to prevent (even though it's fast) having to call `sol.predict_deprojected(sol.q)` multiple times when plotting. I agree it's still good to have `predict_deprojected` be a function. Adding the evaluation of that function to `sol` would I think be helpful though.

For 2.2: I see what you mean. We could still make the new function a `_blah`, but I think this is better than embedding what is an independent functionality inside `_build_matrices`.

**Comment by rbooth200** [comment]
Ok, so I will do 1 and 2.1. There is no need to worry about computational efficiency here, but you could always store the result in your plotting script if you need it.

2.2 is a won't fix I'm afraid. The code in _build_matrix is meant to be internal, considered implementation dependent (might change in the future without warning), and no external interface should call that function or depend on it. De-projecting the visibilities is cheap, just call the geometry.apply_correction function or geometry.deproject, depending what you need (normally it is the latter).

**Comment by rbooth200** [comment]
I've done this
