### ISSUE TITLE
Ensure code uses RA, Dec sign convention consistent with galario

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#57]
Update docstrings in `geometry.py` that note the sign convention

**Comment by rbooth200** [comment]
I've just looked into this. The convention that we are currently using for the phase shifts is the same as uvplot. 

However, uvplot and galario both use the same functional form. This leads to different signs for the dRA and dDec because frank / uv plot are shifting the observation to the phase centre whereas galario is shifting the model away from the phase centre.

My understanding of the meaning of dRA and dDec in galario is that they define a vector pointing from the phase centre to the location of the source. I believe that this is the sensible definition for dRA and dDec. 

Should we update the code and documents accordingly? This would mean flipping the signs of phi in [`apply_phase_shift](https://github.com/discsim/frank/blob/ee8c3447d41030a2f64070c1e6c702353b0c54c5/frank/geometry.py#L64) and adding to the documentation of the geometry classes that dRA and dDec specify the location of the source relative to the phase centre.

**Comment by rbooth200** [comment]
Actually, perhaps a more 'correct' solution is to replace 
```
        Vp = apply_phase_shift(u, v, V, self._dRA, self._dDec)
```
with
```
        Vp = apply_phase_shift(u, v, V, self._dRA, self._dDec, inverse=True)
```
in `apply_correction` (and do the opposite for `undo_correction`).

Another question is whether these functions are named clearly enough. Suggestions welcome!

**Comment by jeffjennings** [comment]
I wonder if the most robust solution would just be to add a parameter to `default_parameters.json`:

```
"sign_convention": "Whether the phase offset (the sign of dRA and dDec) is specified as a vector from the origin to the source, or from the source to the origin.",
```

where the options are `from_origin` and `to_origin`. This would allow us to leave the code as-is, including `apply_correction` and `undo_correction`, just requiring an additional argument, `sign_convention`, to `apply_phase_shift`. In this case I'd be inclined to leave the current sign convention as-is; since it differs between `uvplot` and `galario`, and I've seen both conventions used in the literature, I'm not sure one is much more common than the other.

**Comment by rbooth200** [comment]
>I've seen both conventions used in the literature, I'm not sure one is much more common than the other.

Can you point me to some examples?

**Comment by jeffjennings** [comment]
The DSHARP papers use the 'from_origin' convention...I recall seeing but can't place from where an example that uses 'from_source'. Maybe it would be best to set the default convention in `apply_phase_shift` as `from_origin`...I do think though it would be good to have `sign_convention` as an argument, and to keep this separate from `inverse` so that the calls in `apply_correction` and `undo_correction` don't need to change.

**Comment by rbooth200** [comment]
Since the `from origin convention' is the one that makes the most sense and is used by galario and DSHARP, I'm inclined to go with that unless you can find a bunch of examples using the opposite.

**Comment by rbooth200** [comment]
I'm actually against having an argument choosing the convention since it will only cause confusion.

**Comment by jeffjennings** [comment]
ok; I would still keep the changes isolated to `apply_phase_shift` and keep `inverse=False` by default (even though it requires redefining `inverse` in the docstring) because it seems confusing to have `inverse=True` by default.

**Comment by rbooth200** [comment]
I'll open a PR, let me know what you think there
