### ISSUE TITLE
Definitions of the inclination and position angle

### ISSUE THREAD

**Issue by bjnorfolk** [discsim/frank#90]
Hi again,

I'm very confused on your definitions of the inclination and position angle. I'm fitting HD100453 and I've forked the frank code and printed the inc and PA. The code prints:
![image](https://user-images.githubusercontent.com/34231154/77597095-e4360100-6f51-11ea-939f-28133a07928d.png)
However the known inc and PA of the disc is 29.5 and 151.0 from van der Plas 2019.
Is this contradiction simply in the way you define inc and PA?
Cheers,
Brodie

**Comment by rbooth200** [comment]
Hi Brodie,

I don't think the problem is to do with the definitions  (though we've been lazy and not worried about restricting the fit inclination to +- 90 degrees). 

I suspect instead that the fit is unreliable because the Gaussian used to determine the geometry is a poor match to the shape of the brightness in HD 100453, which has a hole in the middle. So, if you are content with the published geometry I would use that instead. Can you check / confirm that the profile looks reasonable with the published geometry?

If you need an independent way to determine the geometry, I have been working on a non-parametric way to do the fit. It is quite time consuming though!

**Comment by bjnorfolk** [comment]
Hi Richard,

Thanks for all the replies!
See this is where I'm confused because the fit I believe is very accurate, if you look at the radial profile it's a gaussian ring and the visibilities are fit perfectly 
![image](https://user-images.githubusercontent.com/34231154/77633876-330c8680-6fa4-11ea-8d35-ab0bd7ed1567.png)
But from my understanding the inc and PA are integral to making the vis curve fit the data?

**Comment by rbooth200** [comment]
Frank will find a good fit to the deprojected visibilities, even if the inclination is wrong. Can you compare plots using the two different geometries?

**Comment by bjnorfolk** [comment]
Hi Robert, our conversation in my other submitted issue solved this - thanks!
